apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: chat-app-backend-ns
  labels:
    app: backend-chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-chat-app
  template:
    metadata:
      labels:
        app: backend-chat-app
    spec:
      containers:
      - name: chat-app-backend
        image: alokmishra773/chat-app-backend:latest
        ports:
          - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: MONGO_DB_URI
            valueFrom:
              secretKeyRef:
                name: backend-keys
                key: uri
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-keys
                key: token  

            
